//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Request {
    
    private Claim[] claimField;
    
    private Membership membershipField;
    
    private ClaimTotals claimTotalsField;
    
    private Line[] lineField;
    
    private Diagnosis[] diagnosisField;
    
    private HealthCloudScore[] healthCloudScoreField;
    
    private Atc[] atcField;
    
    private Messaging[] messagingField;
    
    private TreatmentProtocol[] treatmentProtocolField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Claim")]
    public Claim[] Claim {
        get {
            return this.claimField;
        }
        set {
            this.claimField = value;
        }
    }
    
    /// <remarks/>
    public Membership Membership {
        get {
            return this.membershipField;
        }
        set {
            this.membershipField = value;
        }
    }
    
    /// <remarks/>
    public ClaimTotals ClaimTotals {
        get {
            return this.claimTotalsField;
        }
        set {
            this.claimTotalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public Line[] Line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Diagnosis")]
    public Diagnosis[] Diagnosis {
        get {
            return this.diagnosisField;
        }
        set {
            this.diagnosisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HealthCloudScore")]
    public HealthCloudScore[] HealthCloudScore {
        get {
            return this.healthCloudScoreField;
        }
        set {
            this.healthCloudScoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Atc")]
    public Atc[] Atc {
        get {
            return this.atcField;
        }
        set {
            this.atcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Messaging")]
    public Messaging[] Messaging {
        get {
            return this.messagingField;
        }
        set {
            this.messagingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TreatmentProtocol")]
    public TreatmentProtocol[] TreatmentProtocol {
        get {
            return this.treatmentProtocolField;
        }
        set {
            this.treatmentProtocolField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Claim {
    
    private string claimIdField;
    
    private string planCodeField;
    
    private string providerTypeField;
    
    private string providerBHFField;
    
    private string providerNameField;
    
    private string prescribingProviderBHFField;
    
    private string prescribingProviderNameField;
    
    private string transactionNoField;
    
    private string referringProviderBHFField;
    
    private string referringProviderNameField;
    
    private string authorisationNoField;
    
    private string inHospitalClaimField;
    
    private double receiptAmountField;
    
    private string providerSubmittedIndField;
    
    private System.DateTime transactionDateField;
    
    private string numLinesField;
    
    private string itemCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string claimId {
        get {
            return this.claimIdField;
        }
        set {
            this.claimIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string planCode {
        get {
            return this.planCodeField;
        }
        set {
            this.planCodeField = value;
        }
    }
    
    /// <remarks/>
    public string providerType {
        get {
            return this.providerTypeField;
        }
        set {
            this.providerTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string providerBHF {
        get {
            return this.providerBHFField;
        }
        set {
            this.providerBHFField = value;
        }
    }
    
    /// <remarks/>
    public string providerName {
        get {
            return this.providerNameField;
        }
        set {
            this.providerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string prescribingProviderBHF {
        get {
            return this.prescribingProviderBHFField;
        }
        set {
            this.prescribingProviderBHFField = value;
        }
    }
    
    /// <remarks/>
    public string prescribingProviderName {
        get {
            return this.prescribingProviderNameField;
        }
        set {
            this.prescribingProviderNameField = value;
        }
    }
    
    /// <remarks/>
    public string transactionNo {
        get {
            return this.transactionNoField;
        }
        set {
            this.transactionNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string referringProviderBHF {
        get {
            return this.referringProviderBHFField;
        }
        set {
            this.referringProviderBHFField = value;
        }
    }
    
    /// <remarks/>
    public string referringProviderName {
        get {
            return this.referringProviderNameField;
        }
        set {
            this.referringProviderNameField = value;
        }
    }
    
    /// <remarks/>
    public string authorisationNo {
        get {
            return this.authorisationNoField;
        }
        set {
            this.authorisationNoField = value;
        }
    }
    
    /// <remarks/>
    public string inHospitalClaim {
        get {
            return this.inHospitalClaimField;
        }
        set {
            this.inHospitalClaimField = value;
        }
    }
    
    /// <remarks/>
    public double receiptAmount {
        get {
            return this.receiptAmountField;
        }
        set {
            this.receiptAmountField = value;
        }
    }
    
    /// <remarks/>
    public string providerSubmittedInd {
        get {
            return this.providerSubmittedIndField;
        }
        set {
            this.providerSubmittedIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime transactionDate {
        get {
            return this.transactionDateField;
        }
        set {
            this.transactionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string numLines {
        get {
            return this.numLinesField;
        }
        set {
            this.numLinesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string itemCount {
        get {
            return this.itemCountField;
        }
        set {
            this.itemCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RuleMessage {
    
    private string runDateTimeField;
    
    private string ruleNoField;
    
    private string packageDescriptionField;
    
    private string messageCodeField;
    
    private string messageNarrativeField;
    
    private string severityField;
    
    private string memberNoField;
    
    private string claimIdField;
    
    private string lineNoField;
    
    /// <remarks/>
    public string runDateTime {
        get {
            return this.runDateTimeField;
        }
        set {
            this.runDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ruleNo {
        get {
            return this.ruleNoField;
        }
        set {
            this.ruleNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string packageDescription {
        get {
            return this.packageDescriptionField;
        }
        set {
            this.packageDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string messageCode {
        get {
            return this.messageCodeField;
        }
        set {
            this.messageCodeField = value;
        }
    }
    
    /// <remarks/>
    public string messageNarrative {
        get {
            return this.messageNarrativeField;
        }
        set {
            this.messageNarrativeField = value;
        }
    }
    
    /// <remarks/>
    public string severity {
        get {
            return this.severityField;
        }
        set {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    public string memberNo {
        get {
            return this.memberNoField;
        }
        set {
            this.memberNoField = value;
        }
    }
    
    /// <remarks/>
    public string claimId {
        get {
            return this.claimIdField;
        }
        set {
            this.claimIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string lineNo {
        get {
            return this.lineNoField;
        }
        set {
            this.lineNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StratificationResult {
    
    private string categoryField;
    
    private double scoreField;
    
    /// <remarks/>
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public double score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TreatmentProtocol {
    
    private string treatmentProtocolIdField;
    
    private string memberNoField;
    
    private string protocolAbbreviationField;
    
    private string chronicIndicatorField;
    
    private System.DateTime startDateField;
    
    private System.DateTime endDateField;
    
    private string tariffDescriptionField;
    
    private string tariffCodeField;
    
    private double quantityField;
    
    private string frequencyField;
    
    private string daysSupplyField;
    
    private string instructionField;
    
    private string assignedByField;
    
    private string manualOverideField;
    
    private string providerTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string treatmentProtocolId {
        get {
            return this.treatmentProtocolIdField;
        }
        set {
            this.treatmentProtocolIdField = value;
        }
    }
    
    /// <remarks/>
    public string memberNo {
        get {
            return this.memberNoField;
        }
        set {
            this.memberNoField = value;
        }
    }
    
    /// <remarks/>
    public string protocolAbbreviation {
        get {
            return this.protocolAbbreviationField;
        }
        set {
            this.protocolAbbreviationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string chronicIndicator {
        get {
            return this.chronicIndicatorField;
        }
        set {
            this.chronicIndicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    public string tariffDescription {
        get {
            return this.tariffDescriptionField;
        }
        set {
            this.tariffDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string tariffCode {
        get {
            return this.tariffCodeField;
        }
        set {
            this.tariffCodeField = value;
        }
    }
    
    /// <remarks/>
    public double quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public string frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string daysSupply {
        get {
            return this.daysSupplyField;
        }
        set {
            this.daysSupplyField = value;
        }
    }
    
    /// <remarks/>
    public string instruction {
        get {
            return this.instructionField;
        }
        set {
            this.instructionField = value;
        }
    }
    
    /// <remarks/>
    public string assignedBy {
        get {
            return this.assignedByField;
        }
        set {
            this.assignedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string manualOveride {
        get {
            return this.manualOverideField;
        }
        set {
            this.manualOverideField = value;
        }
    }
    
    /// <remarks/>
    public string providerType {
        get {
            return this.providerTypeField;
        }
        set {
            this.providerTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Messaging {
    
    private string messageIdField;
    
    private string messageCodeField;
    
    private System.DateTime messageDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string messageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public string messageCode {
        get {
            return this.messageCodeField;
        }
        set {
            this.messageCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime messageDate {
        get {
            return this.messageDateField;
        }
        set {
            this.messageDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Atc {
    
    private string atcIDField;
    
    private string lineNoField;
    
    private string codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string atcID {
        get {
            return this.atcIDField;
        }
        set {
            this.atcIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string lineNo {
        get {
            return this.lineNoField;
        }
        set {
            this.lineNoField = value;
        }
    }
    
    /// <remarks/>
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HealthCloudScore {
    
    private string scoreIdField;
    
    private string memberNoField;
    
    private System.DateTime dateField;
    
    private string valueField;
    
    private double certaintyRankField;
    
    private string rationaleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string scoreId {
        get {
            return this.scoreIdField;
        }
        set {
            this.scoreIdField = value;
        }
    }
    
    /// <remarks/>
    public string memberNo {
        get {
            return this.memberNoField;
        }
        set {
            this.memberNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public double certaintyRank {
        get {
            return this.certaintyRankField;
        }
        set {
            this.certaintyRankField = value;
        }
    }
    
    /// <remarks/>
    public string rationale {
        get {
            return this.rationaleField;
        }
        set {
            this.rationaleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Diagnosis {
    
    private string diagnosisIdField;
    
    private string claimIdField;
    
    private string codeField;
    
    private string typeField;
    
    private string qualifierField;
    
    private string icdChapterIDField;
    
    private string icdBlockIDField;
    
    private string icdCategoryIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string diagnosisId {
        get {
            return this.diagnosisIdField;
        }
        set {
            this.diagnosisIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string claimId {
        get {
            return this.claimIdField;
        }
        set {
            this.claimIdField = value;
        }
    }
    
    /// <remarks/>
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string qualifier {
        get {
            return this.qualifierField;
        }
        set {
            this.qualifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string icdChapterID {
        get {
            return this.icdChapterIDField;
        }
        set {
            this.icdChapterIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string icdBlockID {
        get {
            return this.icdBlockIDField;
        }
        set {
            this.icdBlockIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string icdCategoryID {
        get {
            return this.icdCategoryIDField;
        }
        set {
            this.icdCategoryIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Line {
    
    private string lineNoField;
    
    private string claimIdField;
    
    private string lineTypeField;
    
    private string itemCodeTypeField;
    
    private string chargeableCodeField;
    
    private string extendedCodeField;
    
    private string chargeableDescriptionField;
    
    private string resultsField;
    
    private System.DateTime chargeableTreatmentDateField;
    
    private System.DateTime chargeableStartTimeField;
    
    private System.DateTime chargeableEndTimeField;
    
    private string chargeableDurationField;
    
    private string chargeableQuantityField;
    
    private string inHospitalIndField;
    
    private string benefitCodeField;
    
    private double bMIField;
    
    private double bmiHeightField;
    
    private double bmiWeightField;
    
    private double sideField;
    
    private string toothNumbersField;
    
    private string labReferenceNumberField;
    
    private string thirdPartyIndField;
    
    private string dispensingLocationField;
    
    private string mixtureSequenceField;
    
    private string mixtureTypeField;
    
    private string authorisationNoField;
    
    private string daysSuppliedField;
    
    private string dawField;
    
    private string originalScriptNoField;
    
    private string repeatNoField;
    
    private string repeatAuthoriserField;
    
    private string repeatAuthorisedField;
    
    private string treatingProviderBHFField;
    
    private double grossAmountField;
    
    private double nettAmountField;
    
    private double discountAmountField;
    
    private double levyAmountField;
    
    private double copyFeeField;
    
    private double dispensingFeeField;
    
    private double professionalFeeField;
    
    private string containerFeeField;
    
    private double vatAmountField;
    
    private double surchargeAmountField;
    
    private double patientPaidAmountField;
    
    private string payInstructionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string lineNo {
        get {
            return this.lineNoField;
        }
        set {
            this.lineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string claimId {
        get {
            return this.claimIdField;
        }
        set {
            this.claimIdField = value;
        }
    }
    
    /// <remarks/>
    public string lineType {
        get {
            return this.lineTypeField;
        }
        set {
            this.lineTypeField = value;
        }
    }
    
    /// <remarks/>
    public string itemCodeType {
        get {
            return this.itemCodeTypeField;
        }
        set {
            this.itemCodeTypeField = value;
        }
    }
    
    /// <remarks/>
    public string chargeableCode {
        get {
            return this.chargeableCodeField;
        }
        set {
            this.chargeableCodeField = value;
        }
    }
    
    /// <remarks/>
    public string extendedCode {
        get {
            return this.extendedCodeField;
        }
        set {
            this.extendedCodeField = value;
        }
    }
    
    /// <remarks/>
    public string chargeableDescription {
        get {
            return this.chargeableDescriptionField;
        }
        set {
            this.chargeableDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string results {
        get {
            return this.resultsField;
        }
        set {
            this.resultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime chargeableTreatmentDate {
        get {
            return this.chargeableTreatmentDateField;
        }
        set {
            this.chargeableTreatmentDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime chargeableStartTime {
        get {
            return this.chargeableStartTimeField;
        }
        set {
            this.chargeableStartTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime chargeableEndTime {
        get {
            return this.chargeableEndTimeField;
        }
        set {
            this.chargeableEndTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string chargeableDuration {
        get {
            return this.chargeableDurationField;
        }
        set {
            this.chargeableDurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string chargeableQuantity {
        get {
            return this.chargeableQuantityField;
        }
        set {
            this.chargeableQuantityField = value;
        }
    }
    
    /// <remarks/>
    public string inHospitalInd {
        get {
            return this.inHospitalIndField;
        }
        set {
            this.inHospitalIndField = value;
        }
    }
    
    /// <remarks/>
    public string benefitCode {
        get {
            return this.benefitCodeField;
        }
        set {
            this.benefitCodeField = value;
        }
    }
    
    /// <remarks/>
    public double BMI {
        get {
            return this.bMIField;
        }
        set {
            this.bMIField = value;
        }
    }
    
    /// <remarks/>
    public double bmiHeight {
        get {
            return this.bmiHeightField;
        }
        set {
            this.bmiHeightField = value;
        }
    }
    
    /// <remarks/>
    public double bmiWeight {
        get {
            return this.bmiWeightField;
        }
        set {
            this.bmiWeightField = value;
        }
    }
    
    /// <remarks/>
    public double side {
        get {
            return this.sideField;
        }
        set {
            this.sideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string toothNumbers {
        get {
            return this.toothNumbersField;
        }
        set {
            this.toothNumbersField = value;
        }
    }
    
    /// <remarks/>
    public string labReferenceNumber {
        get {
            return this.labReferenceNumberField;
        }
        set {
            this.labReferenceNumberField = value;
        }
    }
    
    /// <remarks/>
    public string thirdPartyInd {
        get {
            return this.thirdPartyIndField;
        }
        set {
            this.thirdPartyIndField = value;
        }
    }
    
    /// <remarks/>
    public string dispensingLocation {
        get {
            return this.dispensingLocationField;
        }
        set {
            this.dispensingLocationField = value;
        }
    }
    
    /// <remarks/>
    public string mixtureSequence {
        get {
            return this.mixtureSequenceField;
        }
        set {
            this.mixtureSequenceField = value;
        }
    }
    
    /// <remarks/>
    public string mixtureType {
        get {
            return this.mixtureTypeField;
        }
        set {
            this.mixtureTypeField = value;
        }
    }
    
    /// <remarks/>
    public string authorisationNo {
        get {
            return this.authorisationNoField;
        }
        set {
            this.authorisationNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string daysSupplied {
        get {
            return this.daysSuppliedField;
        }
        set {
            this.daysSuppliedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string daw {
        get {
            return this.dawField;
        }
        set {
            this.dawField = value;
        }
    }
    
    /// <remarks/>
    public string originalScriptNo {
        get {
            return this.originalScriptNoField;
        }
        set {
            this.originalScriptNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string repeatNo {
        get {
            return this.repeatNoField;
        }
        set {
            this.repeatNoField = value;
        }
    }
    
    /// <remarks/>
    public string repeatAuthoriser {
        get {
            return this.repeatAuthoriserField;
        }
        set {
            this.repeatAuthoriserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string repeatAuthorised {
        get {
            return this.repeatAuthorisedField;
        }
        set {
            this.repeatAuthorisedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string treatingProviderBHF {
        get {
            return this.treatingProviderBHFField;
        }
        set {
            this.treatingProviderBHFField = value;
        }
    }
    
    /// <remarks/>
    public double grossAmount {
        get {
            return this.grossAmountField;
        }
        set {
            this.grossAmountField = value;
        }
    }
    
    /// <remarks/>
    public double nettAmount {
        get {
            return this.nettAmountField;
        }
        set {
            this.nettAmountField = value;
        }
    }
    
    /// <remarks/>
    public double discountAmount {
        get {
            return this.discountAmountField;
        }
        set {
            this.discountAmountField = value;
        }
    }
    
    /// <remarks/>
    public double levyAmount {
        get {
            return this.levyAmountField;
        }
        set {
            this.levyAmountField = value;
        }
    }
    
    /// <remarks/>
    public double copyFee {
        get {
            return this.copyFeeField;
        }
        set {
            this.copyFeeField = value;
        }
    }
    
    /// <remarks/>
    public double dispensingFee {
        get {
            return this.dispensingFeeField;
        }
        set {
            this.dispensingFeeField = value;
        }
    }
    
    /// <remarks/>
    public double professionalFee {
        get {
            return this.professionalFeeField;
        }
        set {
            this.professionalFeeField = value;
        }
    }
    
    /// <remarks/>
    public string containerFee {
        get {
            return this.containerFeeField;
        }
        set {
            this.containerFeeField = value;
        }
    }
    
    /// <remarks/>
    public double vatAmount {
        get {
            return this.vatAmountField;
        }
        set {
            this.vatAmountField = value;
        }
    }
    
    /// <remarks/>
    public double surchargeAmount {
        get {
            return this.surchargeAmountField;
        }
        set {
            this.surchargeAmountField = value;
        }
    }
    
    /// <remarks/>
    public double patientPaidAmount {
        get {
            return this.patientPaidAmountField;
        }
        set {
            this.patientPaidAmountField = value;
        }
    }
    
    /// <remarks/>
    public string payInstruction {
        get {
            return this.payInstructionField;
        }
        set {
            this.payInstructionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ClaimTotals {
    
    private string claimIdField;
    
    private double claimGrossField;
    
    private double claimNettField;
    
    private double claimDiscountField;
    
    private double claimLevyField;
    
    private double claimCopyField;
    
    private double claimDispensingFeeField;
    
    private double claimProfessionalFeeField;
    
    private double claimContainerFeeField;
    
    private double claimVatAmountField;
    
    private double claimSurchargeField;
    
    private double claimPatientPayAmountField;
    
    private string payInstructionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string claimId {
        get {
            return this.claimIdField;
        }
        set {
            this.claimIdField = value;
        }
    }
    
    /// <remarks/>
    public double claimGross {
        get {
            return this.claimGrossField;
        }
        set {
            this.claimGrossField = value;
        }
    }
    
    /// <remarks/>
    public double claimNett {
        get {
            return this.claimNettField;
        }
        set {
            this.claimNettField = value;
        }
    }
    
    /// <remarks/>
    public double claimDiscount {
        get {
            return this.claimDiscountField;
        }
        set {
            this.claimDiscountField = value;
        }
    }
    
    /// <remarks/>
    public double claimLevy {
        get {
            return this.claimLevyField;
        }
        set {
            this.claimLevyField = value;
        }
    }
    
    /// <remarks/>
    public double claimCopy {
        get {
            return this.claimCopyField;
        }
        set {
            this.claimCopyField = value;
        }
    }
    
    /// <remarks/>
    public double claimDispensingFee {
        get {
            return this.claimDispensingFeeField;
        }
        set {
            this.claimDispensingFeeField = value;
        }
    }
    
    /// <remarks/>
    public double claimProfessionalFee {
        get {
            return this.claimProfessionalFeeField;
        }
        set {
            this.claimProfessionalFeeField = value;
        }
    }
    
    /// <remarks/>
    public double claimContainerFee {
        get {
            return this.claimContainerFeeField;
        }
        set {
            this.claimContainerFeeField = value;
        }
    }
    
    /// <remarks/>
    public double claimVatAmount {
        get {
            return this.claimVatAmountField;
        }
        set {
            this.claimVatAmountField = value;
        }
    }
    
    /// <remarks/>
    public double claimSurcharge {
        get {
            return this.claimSurchargeField;
        }
        set {
            this.claimSurchargeField = value;
        }
    }
    
    /// <remarks/>
    public double claimPatientPayAmount {
        get {
            return this.claimPatientPayAmountField;
        }
        set {
            this.claimPatientPayAmountField = value;
        }
    }
    
    /// <remarks/>
    public string payInstruction {
        get {
            return this.payInstructionField;
        }
        set {
            this.payInstructionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Membership {
    
    private string memberNoField;
    
    private string memberInitialsField;
    
    private string memberFirstNameField;
    
    private string memberSurnameField;
    
    private string memberTitleField;
    
    private string beneficiaryInitialsField;
    
    private string beneficiaryFirstNameField;
    
    private string beneficiarySurnameField;
    
    private System.DateTime beneficiaryDOBField;
    
    private string beneficiaryGenderField;
    
    private string beneficiaryIdField;
    
    private string dependentNoField;
    
    private string messagingExcludeIndicatorField;
    
    private string messagingPreferenceField;
    
    /// <remarks/>
    public string memberNo {
        get {
            return this.memberNoField;
        }
        set {
            this.memberNoField = value;
        }
    }
    
    /// <remarks/>
    public string memberInitials {
        get {
            return this.memberInitialsField;
        }
        set {
            this.memberInitialsField = value;
        }
    }
    
    /// <remarks/>
    public string memberFirstName {
        get {
            return this.memberFirstNameField;
        }
        set {
            this.memberFirstNameField = value;
        }
    }
    
    /// <remarks/>
    public string memberSurname {
        get {
            return this.memberSurnameField;
        }
        set {
            this.memberSurnameField = value;
        }
    }
    
    /// <remarks/>
    public string memberTitle {
        get {
            return this.memberTitleField;
        }
        set {
            this.memberTitleField = value;
        }
    }
    
    /// <remarks/>
    public string beneficiaryInitials {
        get {
            return this.beneficiaryInitialsField;
        }
        set {
            this.beneficiaryInitialsField = value;
        }
    }
    
    /// <remarks/>
    public string beneficiaryFirstName {
        get {
            return this.beneficiaryFirstNameField;
        }
        set {
            this.beneficiaryFirstNameField = value;
        }
    }
    
    /// <remarks/>
    public string beneficiarySurname {
        get {
            return this.beneficiarySurnameField;
        }
        set {
            this.beneficiarySurnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime beneficiaryDOB {
        get {
            return this.beneficiaryDOBField;
        }
        set {
            this.beneficiaryDOBField = value;
        }
    }
    
    /// <remarks/>
    public string beneficiaryGender {
        get {
            return this.beneficiaryGenderField;
        }
        set {
            this.beneficiaryGenderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string beneficiaryId {
        get {
            return this.beneficiaryIdField;
        }
        set {
            this.beneficiaryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string dependentNo {
        get {
            return this.dependentNoField;
        }
        set {
            this.dependentNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string messagingExcludeIndicator {
        get {
            return this.messagingExcludeIndicatorField;
        }
        set {
            this.messagingExcludeIndicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string messagingPreference {
        get {
            return this.messagingPreferenceField;
        }
        set {
            this.messagingPreferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Response {
    
    private StratificationResult[] stratificationResultField;
    
    private RuleMessage[] ruleMessageField;
    
    private TreatmentProtocol[] treatmentProtocolField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StratificationResult")]
    public StratificationResult[] StratificationResult {
        get {
            return this.stratificationResultField;
        }
        set {
            this.stratificationResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RuleMessage")]
    public RuleMessage[] RuleMessage {
        get {
            return this.ruleMessageField;
        }
        set {
            this.ruleMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TreatmentProtocol")]
    public TreatmentProtocol[] TreatmentProtocol {
        get {
            return this.treatmentProtocolField;
        }
        set {
            this.treatmentProtocolField = value;
        }
    }
}
